Makingthe HttpSessionFilter pattern configurable
micronaut-projects/micronaut-session pull request #206
Opened 2024-11-04 14:36 UTC by ChaimaaeROUAI

Fixing the issue #171

2024-11-04 14:51 UTC, sdelamo requested changes
It misses tests

2024-11-06 12:24 UTC, sdelamo requested changes
Can you add a test with verifies that you can configure certain paths to be excluded by the filter?

2024-12-11 10:36 UTC, sdelamo commented
sonar code coverage is incorrect. The PR includes tests which set `enabled` to false and the `regex-pattern`

2025-01-02 07:13 UTC, yawkat approved these changes

2025-01-02 09:38 UTC, merged